### ISSUE TITLE
Build fails on Japanese Windows

### ISSUE THREAD

**Issue by sakurai-youhei** [jbmohler/matplotlib-winbuild#6]
Unless `encoding="UTF-8"` is specified at following locations, build fails due to below error. 
https://github.com/jbmohler/matplotlib-winbuild/blob/master/utils.py#L34
https://github.com/jbmohler/matplotlib-winbuild/blob/master/utils.py#L37

```
Traceback (most recent call last):
  File "matplotlib-winbuild\buildall.py", line 58, in <module>
    main(options)
  File "matplotlib-winbuild\buildall.py", line 13, in main
    utils.build_freetype()
  File "C:\Users\homeuser\matplotlib-winbuild\utils.py", line 219, in build_freetype
    fixproj(os.path.join(ft_dir, 'builds', 'win32', vc, 'freetype.sln'), WinXX)
  File "C:\Users\homeuser\matplotlib-winbuild\utils.py", line 35, in fixproj
    content = '\n'.join(line.strip() for line in fd if line.strip())
  File "C:\Users\homeuser\matplotlib-winbuild\utils.py", line 35, in <genexpr>
    content = '\n'.join(line.strip() for line in fd if line.strip())
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
```

**Comment by pbandj082** [comment]
in line 34 and line 37, you should add encoding='utf-8' at open function argument
open関数の文字コードをutf-8にしたら直りました、
